// 应用常量
export const APP_CONFIG = {
  DEFAULT_SCAN_COUNT: 200,
  DEFAULT_PAGE_SIZE: 100,
  MAX_VALUE_DISPLAY_SIZE: 1024 * 1024, // 1MB
  COMMAND_TIMEOUT: 5000,
  HEARTBEAT_INTERVAL: 30000,
  RECONNECT_BASE_DELAY: 1000,
  RECONNECT_MAX_DELAY: 30000,
  METRICS_REFRESH_INTERVAL: 3000,
  SLOWLOG_REFRESH_INTERVAL: 10000,
  MAX_PARALLEL_CONNECTIONS: 20,
  VIRTUAL_LIST_ROW_HEIGHT: 36,
  PREFETCH_THRESHOLD: 100,
} as const;

// 危险命令列表
export const DANGEROUS_COMMANDS = [
  'FLUSHALL',
  'FLUSHDB',
  'CONFIG',
  'DEBUG',
  'SHUTDOWN',
  'SLAVEOF',
  'REPLICAOF',
  'MODULE',
] as const;
